#!/usr/bin/env python3
"""Write a UE 5.4 `.pak` container, version 11, unencrypted index (plan.md task CT-01).

WHY THIS EXISTS
---------------
CT-05 asks whether Shipping MISERY can discover and load an EXTERNAL cooked
package. That question has a well-known trap: if the game does not load our
container, there are two incompatible explanations --

    (a) the loader rejected a perfectly valid container, or
    (b) our serializer produced a container that was never valid.

A negative CT-05 result is worth nothing unless (b) is excluded. This writer is
half of how (b) gets excluded; the other half is `UnrealPak.exe`, which
`research/decisions.md` D-10 explicitly pre-authorises as an independent oracle
for exactly this cross-validation ("UnrealPak.exe доступен как независимый
oracle для нашего pak_writer.py немедленно -- а это cross-validation Tier A, не
производство контента"). Running this writer's own `--self-test` plus
`UnrealPak <file> -Test` gives two independent verdicts on the same bytes.

WHAT THIS IS NOT
----------------
This writes a *file container*. It does not cook, and a `.pak` alone carries
files, not packages: in this build the package loader takes packages only from
an IoStore container header, and `.utoc` is picked up only as a file-neighbour
of a mounted `.pak` (`sp1-static-proxy.md` §8 п. 1, `IPlatformFilePak.cpp:8564`).
So a `.pak` produced here answers "is a container discovered and mounted",
never "is a package loaded". Keeping those two questions apart is the point.

FORMAT SOURCES
--------------
Every field below is cited to one of:
  H  Runtime/PakFile/Public/IPlatformFilePak.h
  C  Runtime/PakFile/Private/IPlatformFilePak.cpp
  U  Developer/PakFileUtilities/Private/PakFileUtilities.cpp
in UE 5.4.4 CL 35576357, the changelist this build was made with. The layout was
additionally confirmed empirically against a reference container generated by
this machine's own `UnrealPak.exe` and against the shipped `MISERY-Windows.pak`
(also v11) -- see `research/evidence/CT-05/`.

THREE PLACES THIS FORMAT PUNISHES A CARELESS WRITER
---------------------------------------------------
1. **The footer is written in a different order than it is declared.**
   `FPakInfo::GetSerializedSize` (H:193-201) sums fields in declaration order;
   `FPakInfo::Serialize` (H:215-303) writes them in another. Both give 221
   bytes for v11, so a writer that follows the declaration order produces a
   correctly-SIZED and completely WRONG footer. Discovery does not search for
   the magic -- it computes `TotalSize - GetSerializedSize(v)` (C:5989-6017) --
   so the failure is silent. The order used below is the `Serialize` order.

2. **The path-hash blob holds TWO structures, not one.** `U:3175-3176` writes
   the path-hash map AND a pruned directory index into the same blob, and
   `C:6285`/`C:6296` read both back sequentially from one reader. In a Shipping
   build `C:6296` DOES run. A blob containing only the map leaves the reader at
   EOF and the mount fails. Neither `pak_index.py` nor `container_info.py`
   would catch this -- they SHA-1 the blob and never parse it -- so this is
   precisely a defect that would have survived our own acceptance criterion and
   then been misread as "the loader rejected us".

3. **The v11 path hash is FNV-1a-64 with the seed ADDED to the offset basis**
   (`FFnv::MemFnv64`, Fnv.cpp:26-42), over the lowercased path encoded UTF-16LE
   with NO terminator. v11 is literally named `PakFile_Version_Fnv64BugFix`
   (H:137-155) because versions below it transposed the offset and prime
   constants. Using the pre-11 pair yields a structurally valid pak in which
   every single lookup misses. Nothing in our parsers checks this either, which
   is why `--self-test` verifies it here.

D-01
----
Refuses any output path inside a known game installation, via the same
`pathguard` module every other tool in this repository uses -- never a
reimplemented check.
"""
import argparse
import hashlib
import io
import json
import os
import struct
import sys
import zlib

_HERE = os.path.dirname(os.path.abspath(__file__))
_TOOLS = os.path.dirname(_HERE)
for _extra in (os.path.join(_TOOLS, "inventory"),):
    if _extra not in sys.path:
        sys.path.insert(0, _extra)

# Shared output-path guard -- plan.md 1.5 layer 1 / D-01. Imported, never
# reimplemented, exactly as pak_index.py does it.
import pathguard  # noqa: E402  (sys.path is prepared just above)

GENERATOR_NAME = "pak_writer.py"
GENERATOR_VERSION = "1.0.0"

# H:127. Written as a uint32; on disk little-endian this reads E1 12 6F 5A.
PAK_MAGIC = 0x5A6F12E1

# H:137-155. 11 == PakFile_Version_Fnv64BugFix == PakFile_Version_Latest in
# 5.4.4, and also the version the shipped MISERY-Windows.pak carries.
PAK_VERSION_FNV64_BUGFIX = 11

# H:131,133 -- 5 slots of 32 ANSI chars each, all zero when nothing is
# compressed. Index 0 is always NAME_None and is never serialised (H:184-185).
COMPRESSION_METHOD_NAME_LEN = 32
MAX_NUM_COMPRESSION_METHODS = 5

# Fnv.cpp:26-42.
FNV64_OFFSET = 0xCBF29CE484222325
FNV64_PRIME = 0x00000100000001B3
U64_MASK = 0xFFFFFFFFFFFFFFFF

# H:417-444 for v11, uncompressed: 8+8+8+4+20+1+4.
LOCAL_HEADER_SIZE_V11 = 53

# The canonical UE relative mount point: paths inside the container are
# relative to <Install>/, because the process base dir is
# <Install>/<Project>/Binaries/Win64/. This is what MISERY-Windows.pak uses.
DEFAULT_MOUNT_POINT = "../../../"


class PakWriteError(Exception):
    """Refuse to emit a container we cannot vouch for."""


# --------------------------------------------------------------------------- #
# primitives
# --------------------------------------------------------------------------- #

def fstring(text: str) -> bytes:
    """FString on the wire (String.cpp.inl:1873-1913).

    int32 count, then the characters INCLUDING the terminating NUL:
      count > 0  -> ANSI, `count` bytes
      count < 0  -> UTF-16LE, `-count` code units
      count == 0 -> the empty string, and nothing follows

    The empty string is four zero bytes, NOT a length of 1 with a NUL: the
    save path takes `Num = Data.Num()`, and an empty FString has an empty
    Data array (:1906).
    """
    if text == "":
        return struct.pack("<i", 0)
    if all(ord(ch) < 128 for ch in text):
        raw = text.encode("ascii") + b"\x00"
        return struct.pack("<i", len(raw)) + raw
    raw = text.encode("utf-16-le") + b"\x00\x00"
    return struct.pack("<i", -(len(raw) // 2)) + raw


def fnv64(data: bytes, seed: int) -> int:
    """FFnv::MemFnv64 (Fnv.cpp:26-42). Note the seed is ADDED to the offset
    basis, not XOR-folded into the running hash."""
    value = (FNV64_OFFSET + seed) & U64_MASK
    for byte in data:
        value ^= byte
        value = (value * FNV64_PRIME) & U64_MASK
    return value


def hash_path(relative_path: str, seed: int) -> int:
    """FPakFile::HashPath (C:6521-6533) for version >= 11.

    Lowercased, UTF-16LE, `Len() * sizeof(TCHAR)` bytes -- Len() excludes the
    terminator, so no NUL is hashed.
    """
    return fnv64(relative_path.lower().encode("utf-16-le"), seed)


def str_crc32(text: str) -> int:
    """FCrc::StrCrc32 (Crc.h:44-65): reflected CRC-32 over the string's UTF-32LE
    code units -- the loop consumes 4 bytes per character regardless of
    sizeof(TCHAR).

    Used only to derive a default path-hash seed the way UnrealPak does
    (C:6540-6550). The seed is stored in the index and read back from it
    (C:6152), so ANY uint64 is legal; only internal consistency matters.
    """
    return zlib.crc32(text.encode("utf-32-le")) & 0xFFFFFFFF


def split_path_inline(relative_path: str) -> tuple:
    """FPakFile::SplitPathInline (H:1480-1528).

    A path with no separator lives in the directory spelled "/" (H:1520-1525).
    """
    cut = relative_path.rfind("/")
    if cut < 0:
        return "/", relative_path
    return relative_path[:cut + 1], relative_path[cut + 1:]


def parent_directories(directory: str) -> list:
    """Every ancestor AddEntryToIndex would FindOrAdd (C:6906-6931).

    The engine walks from the file's own directory up to and including the
    root, creating each. Ancestors created this way hold zero files and must
    still appear in the index as empty entries.
    """
    out = []
    current = directory
    while True:
        stripped = current.rstrip("/")
        cut = stripped.rfind("/")
        if current == "/" or cut < 0:
            break
        current = stripped[:cut + 1]
        out.append(current)
    if directory != "/":
        out.append("/")
    return out


# --------------------------------------------------------------------------- #
# record encoders
# --------------------------------------------------------------------------- #

def local_header(size: int, uncompressed_size: int, sha1: bytes) -> bytes:
    """FPakEntry::Serialize (H:495-544) for v11, uncompressed.

    Two things routinely get written wrong here and both are silent:
      * `Offset` is literally zero. UnrealPak sets it to 0 with the comment
        "Don't serialize offsets here" (U:1036) and stores the real offset
        only in the index (U:2750).
      * `Hash` sits AFTER CompressionMethodIndex and BEFORE Flags -- not at
        the end of the record.
    """
    if len(sha1) != 20:
        raise PakWriteError("SHA-1 must be 20 raw bytes, got %d" % len(sha1))
    return (struct.pack("<qqq", 0, size, uncompressed_size)
            + struct.pack("<I", 0)          # CompressionMethodIndex = None
            + sha1
            + struct.pack("<B", 0)          # Flags: not encrypted, not deleted
            + struct.pack("<I", 0))         # CompressionBlockSize


def encode_entry(offset: int, uncompressed_size: int) -> bytes:
    """FPakFile::EncodePakEntry (C:6952-7090), uncompressed + unencrypted case.

    Bit layout of the header word (C:7023-7031, documented C:7094-7101):
      31    offset fits in uint32        30    uncompressed size fits in uint32
      29    size fits in uint32          28-23 compression method index
      22    encrypted                    21-6  compression block count
      5-0   packed compression block size

    For method 0 the `Size` field is NOT emitted at all (C:7065) -- it is
    defined to equal UncompressedSize (C:7168-7170). Emitting it anyway shifts
    every following byte, which is the kind of error that still parses.
    """
    if offset > 0xFFFFFFFF or uncompressed_size > 0xFFFFFFFF:
        raise PakWriteError(
            "this writer emits only the 32-bit-field form; offset=%d size=%d "
            "exceed it. Supporting >4GiB means emitting int64 fields per "
            "C:7043-7062 and is deliberately not guessed at here."
            % (offset, uncompressed_size))
    word = (1 << 31) | (1 << 30) | (1 << 29)   # all three fit in uint32
    # method 0, not encrypted, zero blocks, packed block size 0 -> 0xE0000000
    return (struct.pack("<I", word & 0xFFFFFFFF)
            + struct.pack("<I", offset)
            + struct.pack("<I", uncompressed_size))


def serialize_directory_index(directory_index: dict) -> bytes:
    """FDirectoryIndex = TMap<FString, TMap<FString, FPakEntryLocation>> (H:729).

    TMap on the wire is int32 count then the pairs (Map.h:1937 -> Set.h:2199 ->
    SparseArray.h:1489-1504 -> Tuple.h:446-450); the hash table is rebuilt on
    load (Set.h:2204-2212), so order is free. Sorted here purely so the output
    is byte-reproducible run to run.
    """
    out = struct.pack("<i", len(directory_index))
    for directory in sorted(directory_index):
        files = directory_index[directory]
        out += fstring(directory) + struct.pack("<i", len(files))
        for name in sorted(files):
            out += fstring(name) + struct.pack("<i", files[name])
    return out


def serialize_path_hash_blob(path_hash: dict, pruned_directory_index: dict) -> bytes:
    """The path-hash blob: the map AND a pruned directory index (U:3175-3176).

    See this module's docstring, trap 2. The second structure is mandatory --
    C:6296 reads it in a Shipping build, and omitting it fails the mount while
    passing every check our own parsers make.
    """
    out = struct.pack("<i", len(path_hash))
    for key in sorted(path_hash):
        out += struct.pack("<Qi", key, path_hash[key])
    out += serialize_directory_index(pruned_directory_index)
    return out


# --------------------------------------------------------------------------- #
# the writer
# --------------------------------------------------------------------------- #

def build_pak(entries: list, *, mount_point: str = DEFAULT_MOUNT_POINT,
              seed: int | None = None, seed_source: str | None = None,
              prune_directory_index: bool = True) -> dict:
    """Serialise *entries* -- a list of (relative_path, payload_bytes) -- into
    a complete v11 container. Returns {'bytes', 'layout', 'seed', ...}.

    *prune_directory_index* True writes an EMPTY pruned index into the
    path-hash blob, which is what a default-configured UnrealPak produces
    (PruneDirectoryIndex takes the else branch at C:6722-6728 when no
    [Pak] DirectoryIndexKeepFiles config exists). False duplicates the full
    index there instead, which makes directory enumeration work in Shipping
    too. The shipped MISERY-Windows.pak has a POPULATED pruned index, so that
    build does set the config -- recorded here because it is a visible
    shape difference if anything ever fingerprints our container.
    """
    if not entries:
        raise PakWriteError("refusing to write a container with zero entries")
    if not mount_point.endswith("/"):
        raise PakWriteError(
            "mount point must be in directory format (end with '/'); "
            "AddEntryToIndex check()s this at C:6899, got %r" % mount_point)

    if seed is None:
        seed = str_crc32((seed_source or "pak_writer").lower())

    body = io.BytesIO()
    encoded = io.BytesIO()
    directory_index: dict = {}
    path_hash: dict = {}

    for relative_path, payload in entries:
        if relative_path.startswith("/"):
            raise PakWriteError(
                "index paths are relative to the mount point and carry no "
                "leading slash; got %r" % relative_path)
        entry_offset = body.tell()
        body.write(local_header(len(payload), len(payload),
                                hashlib.sha1(payload).digest()))
        body.write(payload)

        location = encoded.tell()          # FPakEntryLocation == byte offset
        encoded.write(encode_entry(entry_offset, len(payload)))

        directory, filename = split_path_inline(relative_path)
        directory_index.setdefault(directory, {})[filename] = location
        for ancestor in parent_directories(directory):
            directory_index.setdefault(ancestor, {})
        path_hash[hash_path(relative_path, seed)] = location

    if len(path_hash) != len(entries):
        raise PakWriteError(
            "path-hash collision or duplicate path: %d entries produced %d "
            "distinct hashes" % (len(entries), len(path_hash)))

    encoded_bytes = encoded.getvalue()
    path_hash_blob = serialize_path_hash_blob(
        path_hash, {} if prune_directory_index else directory_index)
    full_directory_blob = serialize_directory_index(directory_index)
    index_offset = body.tell()

    def primary(ph_off, ph_size, ph_hash, fd_off, fd_size, fd_hash) -> bytes:
        """Primary index, field order per C:6087-6202 / U:3147-3164.

        `bool` here is 4 bytes: FArchive::SerializeBool writes a legacy 32-bit
        UBOOL (Archive.cpp:495-519). The footer's bEncryptedIndex, by contrast,
        is a genuine 1-byte uint8. The format really does mix both widths.
        """
        out = fstring(mount_point)
        out += struct.pack("<i", len(entries))
        out += struct.pack("<Q", seed)
        out += struct.pack("<I", 1) + struct.pack("<qq", ph_off, ph_size) + ph_hash
        out += struct.pack("<I", 1) + struct.pack("<qq", fd_off, fd_size) + fd_hash
        out += struct.pack("<i", len(encoded_bytes)) + encoded_bytes
        out += struct.pack("<i", 0)        # NonEncodableEntriesNum
        return out

    # The secondary blobs sit immediately after the primary index, so their
    # offsets depend on its length -- which does not depend on their values.
    # Serialise once with placeholders to measure, then again for real.
    zero20 = b"\x00" * 20
    measured = len(primary(0, 0, zero20, 0, 0, zero20))
    path_hash_offset = index_offset + measured
    full_directory_offset = path_hash_offset + len(path_hash_blob)
    primary_blob = primary(
        path_hash_offset, len(path_hash_blob), hashlib.sha1(path_hash_blob).digest(),
        full_directory_offset, len(full_directory_blob),
        hashlib.sha1(full_directory_blob).digest())
    if len(primary_blob) != measured:
        raise PakWriteError(
            "primary index length changed between the measuring pass (%d) and "
            "the real pass (%d); the secondary offsets would be wrong"
            % (measured, len(primary_blob)))

    footer = (b"\x00" * 16                                 # EncryptionKeyGuid
              + b"\x00"                                    # bEncryptedIndex (uint8)
              + struct.pack("<I", PAK_MAGIC)
              + struct.pack("<i", PAK_VERSION_FNV64_BUGFIX)
              + struct.pack("<q", index_offset)
              + struct.pack("<q", len(primary_blob))
              + hashlib.sha1(primary_blob).digest()
              + b"\x00" * (COMPRESSION_METHOD_NAME_LEN * MAX_NUM_COMPRESSION_METHODS))
    expected_footer = 61 + COMPRESSION_METHOD_NAME_LEN * MAX_NUM_COMPRESSION_METHODS
    if len(footer) != expected_footer:
        raise PakWriteError("footer is %d bytes, v11 requires %d"
                            % (len(footer), expected_footer))

    blob = (body.getvalue() + primary_blob + path_hash_blob
            + full_directory_blob + footer)
    return {
        "bytes": blob,
        "seed": seed,
        "mount_point": mount_point,
        "entry_count": len(entries),
        "layout": {
            "body_size": index_offset,
            "index_offset": index_offset,
            "index_size": len(primary_blob),
            "path_hash_index_offset": path_hash_offset,
            "path_hash_index_size": len(path_hash_blob),
            "full_directory_index_offset": full_directory_offset,
            "full_directory_index_size": len(full_directory_blob),
            "footer_offset": len(blob) - len(footer),
            "footer_size": len(footer),
            "total_size": len(blob),
        },
        "path_hash": path_hash,
        "directory_index": directory_index,
    }


# --------------------------------------------------------------------------- #
# self-test -- covers what our own parsers structurally cannot
# --------------------------------------------------------------------------- #

def self_test(built: dict) -> list:
    """Checks this writer must make about its own output, because the two
    project parsers cannot: they SHA-1 the path-hash blob without parsing it,
    and neither recomputes a path hash. A wrong hash function or a missing
    pruned-index tail passes both of them and then fails to mount -- and would
    be misread as the loader rejecting us.

    Returns a list of (name, ok, detail).
    """
    results = []
    blob = built["bytes"]
    layout = built["layout"]

    regions = [
        ("body", 0, layout["body_size"]),
        ("primary", layout["index_offset"], layout["index_size"]),
        ("path_hash", layout["path_hash_index_offset"], layout["path_hash_index_size"]),
        ("full_dir", layout["full_directory_index_offset"], layout["full_directory_index_size"]),
        ("footer", layout["footer_offset"], layout["footer_size"]),
    ]
    cursor = 0
    gaps = []
    for name, off, size in regions:
        if off != cursor:
            gaps.append("%s starts at %d, expected %d" % (name, off, cursor))
        cursor = off + size
    results.append(("layout_tiles_exactly", not gaps and cursor == len(blob),
                    "; ".join(gaps) or "regions cover %d bytes with no gap" % cursor))

    # Footer field offsets follow the Serialize order (H:215-303), NOT the
    # declaration order: guid 0..15, bEncryptedIndex 16, magic 17..20,
    # version 21..24, IndexOffset 25..32, IndexSize 33..40, IndexHash 41..60,
    # CompressionMethods 61..220.
    footer = blob[layout["footer_offset"]:]
    magic = struct.unpack_from("<I", footer, 17)[0]
    version = struct.unpack_from("<i", footer, 21)[0]
    stored_index_offset = struct.unpack_from("<q", footer, 25)[0]
    stored_index_size = struct.unpack_from("<q", footer, 33)[0]
    results.append(("footer_magic", magic == PAK_MAGIC, "0x%08X" % magic))
    results.append(("footer_version", version == PAK_VERSION_FNV64_BUGFIX, str(version)))
    results.append(("footer_encrypted_flag_clear", footer[16] == 0, "byte=%d" % footer[16]))
    results.append(("footer_index_offset_matches_layout",
                    stored_index_offset == layout["index_offset"],
                    "stored %d, layout %d" % (stored_index_offset, layout["index_offset"])))
    results.append(("footer_index_size_matches_layout",
                    stored_index_size == layout["index_size"],
                    "stored %d, layout %d" % (stored_index_size, layout["index_size"])))

    stored = footer[41:61]
    actual = hashlib.sha1(
        blob[layout["index_offset"]:layout["index_offset"] + layout["index_size"]]).digest()
    results.append(("primary_index_sha1", stored == actual,
                    "stored %s" % stored.hex()))

    # The check neither parser makes: every path must hash to an entry.
    ok = True
    detail = []
    for directory, files in built["directory_index"].items():
        for filename, location in files.items():
            relative = filename if directory == "/" else directory + filename
            digest = hash_path(relative, built["seed"])
            if built["path_hash"].get(digest) != location:
                ok = False
                detail.append(relative)
    results.append(("every_path_resolves_via_path_hash", ok,
                    "misses: %s" % (", ".join(detail) if detail else "none")))

    # And the trap the parsers structurally cannot see: the blob must contain
    # the pruned directory index after the map, and be consumed exactly.
    ph = blob[layout["path_hash_index_offset"]:
              layout["path_hash_index_offset"] + layout["path_hash_index_size"]]
    count = struct.unpack_from("<i", ph, 0)[0]
    consumed = 4 + count * 12
    tail_ok = len(ph) >= consumed + 4
    results.append(("path_hash_blob_has_pruned_index_tail", tail_ok,
                    "map=%d bytes, blob=%d bytes, tail present=%s"
                    % (consumed, len(ph), tail_ok)))
    return results


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("out", help="path of the .pak to write (refused inside a game install)")
    parser.add_argument("--add", action="append", default=[], metavar="SRC=DEST",
                        help="a real file SRC stored at container-relative DEST; repeatable")
    parser.add_argument("--add-literal", action="append", default=[], metavar="TEXT=DEST",
                        help="literal ASCII TEXT stored at DEST; repeatable, for probe payloads")
    parser.add_argument("--mount-point", default=DEFAULT_MOUNT_POINT)
    parser.add_argument("--seed", type=lambda v: int(v, 0), default=None,
                        help="path-hash seed; any uint64 is legal (C:6152)")
    parser.add_argument("--keep-full-directory-in-pruned", action="store_true",
                        help="duplicate the full directory index into the path-hash "
                             "blob's pruned slot instead of leaving it empty")
    parser.add_argument("--json", metavar="PATH", help="write a layout/self-test report here")
    args = parser.parse_args(argv)

    try:
        install_root = pathguard.CONFIGURED_INSTALL_ROOTS[0]
    except Exception:  # noqa: BLE001 - guard availability must never be fatal here
        install_root = None
    try:
        target = pathguard.check_output_path(args.out, install_root, what="out")
    except (pathguard.OutputPathRefused, ValueError) as error:
        print("refused: %s" % error, file=sys.stderr)
        return 2

    entries = []
    for spec in args.add:
        src, _, dest = spec.partition("=")
        if not dest:
            print("--add needs SRC=DEST, got %r" % spec, file=sys.stderr)
            return 2
        with open(src, "rb") as handle:
            entries.append((dest.replace("\\", "/"), handle.read()))
    for spec in args.add_literal:
        text, _, dest = spec.partition("=")
        if not dest:
            print("--add-literal needs TEXT=DEST, got %r" % spec, file=sys.stderr)
            return 2
        entries.append((dest.replace("\\", "/"), text.encode("ascii")))

    if not entries:
        print("nothing to add: pass --add or --add-literal", file=sys.stderr)
        return 2

    try:
        built = build_pak(entries, mount_point=args.mount_point, seed=args.seed,
                          seed_source=os.path.basename(target),
                          prune_directory_index=not args.keep_full_directory_in_pruned)
    except PakWriteError as error:
        print("refused: %s" % error, file=sys.stderr)
        return 2

    checks = self_test(built)
    with open(target, "wb") as handle:
        handle.write(built["bytes"])

    print("wrote %s (%d bytes, %d entries, mount %r, seed 0x%016x)"
          % (target, built["layout"]["total_size"], built["entry_count"],
             built["mount_point"], built["seed"]))
    for name, size in (("body", built["layout"]["body_size"]),
                       ("primary index", built["layout"]["index_size"]),
                       ("path hash index", built["layout"]["path_hash_index_size"]),
                       ("full directory index", built["layout"]["full_directory_index_size"]),
                       ("footer", built["layout"]["footer_size"])):
        print("  %-22s %d bytes" % (name, size))
    print("self-test:")
    failed = 0
    for name, ok, detail in checks:
        print("  [%s] %-38s %s" % ("PASS" if ok else "FAIL", name, detail))
        failed += 0 if ok else 1

    if args.json:
        try:
            report_path = pathguard.check_output_path(args.json, install_root, what="json")
        except (pathguard.OutputPathRefused, ValueError) as error:
            print("refused: %s" % error, file=sys.stderr)
            return 2
        report = {
            "generator": {"name": GENERATOR_NAME, "version": GENERATOR_VERSION},
            "target": os.path.basename(target),
            "mount_point": built["mount_point"],
            "seed": "0x%016x" % built["seed"],
            "entry_count": built["entry_count"],
            "layout": built["layout"],
            "self_test": [{"check": n, "ok": ok, "detail": d} for n, ok, d in checks],
            "self_test_failed": failed,
        }
        with open(report_path, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(report, handle, indent=2, sort_keys=True)
            handle.write("\n")
        print("report: %s" % report_path)

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
