#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tests for tools/content/pak_writer.py (plan.md task CT-01 -- write a UE 5.4
`.pak` v11 container with an unencrypted index).

Standard library only, and nothing here touches a game installation or a live
process: every test builds a container in memory, or in tmp_path, and inspects
the bytes.

The tests deliberately concentrate on the three places the format punishes a
careless writer silently -- the ones documented in the tool's own module
docstring, each of which produces a container that our own parsers accept and
the engine does not:

  1. the footer is SERIALISED in a different order than it is DECLARED
     (IPlatformFilePak.h:215-303 vs :193-201), so field-offset tests here are
     written against the serialise order and would fail loudly if someone
     "tidied" the writer into declaration order;
  2. the path-hash blob carries TWO structures -- the hash map AND a pruned
     directory index (PakFileUtilities.cpp:3175-3176) -- and omitting the
     second is invisible to pak_index.py and container_info.py, which SHA-1
     the blob without parsing it;
  3. v11's path hash is FNV-1a-64 with the seed ADDED to the offset basis
     (Fnv.cpp:26-42); versions below 11 transpose the two constants, and using
     the wrong pair yields a structurally perfect pak in which every lookup
     misses.

The reference numbers pinned below (byte sizes, the 0xE0000000 flag word, the
53-byte local header, the 221-byte footer) are not invented for the test: they
were confirmed against a container generated by this machine's own
UnrealPak.exe and against the shipped MISERY-Windows.pak, both v11 --
research/evidence/CT-05/.
"""

from __future__ import annotations

import hashlib
import os
import struct
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO_ROOT, "tools", "content"))

import pak_writer as tool  # noqa: E402


# --------------------------------------------------------------------------- #
# FString -- String.cpp.inl:1873-1913
# --------------------------------------------------------------------------- #

def test_fstring_ansi_includes_terminator():
    # count is Data.Num(), i.e. Len() + 1, and the NUL is on the wire
    assert tool.fstring("abc") == struct.pack("<i", 4) + b"abc\x00"


def test_fstring_empty_is_four_zero_bytes():
    # NOT a count of 1 with a NUL: an empty FString has an empty Data array,
    # so Num() == 0 (String.cpp.inl:1906)
    assert tool.fstring("") == b"\x00\x00\x00\x00"


def test_fstring_non_ascii_switches_to_negative_count_utf16():
    out = tool.fstring("é")
    count = struct.unpack_from("<i", out, 0)[0]
    assert count == -2, "one char plus terminator, as UTF-16 code units"
    assert out[4:] == "é".encode("utf-16-le") + b"\x00\x00"


def test_fstring_mount_point_matches_shipped_container():
    # MISERY-Windows.pak's primary index begins with exactly these 14 bytes
    assert tool.fstring("../../../") == struct.pack("<i", 10) + b"../../../\x00"


# --------------------------------------------------------------------------- #
# the v11 path hash -- FFnv::MemFnv64 (Fnv.cpp:26-42), FPakFile::HashPath (C:6521)
# --------------------------------------------------------------------------- #

def test_fnv64_seed_is_added_to_the_offset_basis_not_xored():
    # The distinguishing property of the v11 ("Fnv64BugFix") variant.
    empty_seeded = tool.fnv64(b"", 5)
    assert empty_seeded == (tool.FNV64_OFFSET + 5) & tool.U64_MASK


def test_fnv64_matches_hand_computed_reference():
    h = (tool.FNV64_OFFSET + 0) & tool.U64_MASK
    for byte in b"a\x00":                      # 'a' as UTF-16LE
        h ^= byte
        h = (h * tool.FNV64_PRIME) & tool.U64_MASK
    assert tool.hash_path("a", 0) == h


def test_hash_path_lowercases_and_uses_utf16_without_terminator():
    assert tool.hash_path("ABC", 7) == tool.hash_path("abc", 7)
    assert tool.hash_path("abc", 7) == tool.fnv64("abc".encode("utf-16-le"), 7)
    # a terminator would change the result -- pin that it is absent
    assert tool.hash_path("abc", 7) != tool.fnv64("abc\x00".encode("utf-16-le"), 7)


def test_hash_path_is_seed_sensitive():
    assert tool.hash_path("x/y.txt", 1) != tool.hash_path("x/y.txt", 2)


def test_legacy_constant_pair_would_differ():
    """Guards the actual v11 bug fix: transposing offset and prime is exactly
    what versions < 11 did, and it still produces a plausible-looking hash."""
    legacy = 0x00000100000001B3
    swapped = ((legacy + 0) ^ ord("a")) & tool.U64_MASK
    swapped = (swapped * 0xCBF29CE484222325) & tool.U64_MASK
    assert tool.hash_path("a", 0) != swapped


# --------------------------------------------------------------------------- #
# path splitting and the parent-directory walk -- H:1480-1528, C:6906-6931
# --------------------------------------------------------------------------- #

def test_split_path_root_level_file_lives_in_slash():
    assert tool.split_path_inline("test.txt") == ("/", "test.txt")


def test_split_path_nested():
    assert tool.split_path_inline("A/B/c.txt") == ("A/B/", "c.txt")


def test_parent_directories_walks_to_root_inclusive():
    parents = tool.parent_directories("A/B/C/")
    assert parents == ["A/B/", "A/", "/"]


def test_parent_directories_of_root_is_empty():
    assert tool.parent_directories("/") == []


# --------------------------------------------------------------------------- #
# record encoders
# --------------------------------------------------------------------------- #

def test_local_header_is_53_bytes_for_v11_uncompressed():
    header = tool.local_header(5, 5, hashlib.sha1(b"hello").digest())
    assert len(header) == tool.LOCAL_HEADER_SIZE_V11 == 53


def test_local_header_offset_field_is_always_zero():
    """UnrealPak writes 0 here ('Don't serialize offsets here', U:1036) and
    stores the real offset only in the index (U:2750)."""
    header = tool.local_header(5, 5, b"\x11" * 20)
    assert struct.unpack_from("<q", header, 0)[0] == 0


def test_local_header_field_order_hash_before_flags():
    """Hash sits AFTER CompressionMethodIndex and BEFORE Flags -- not at the
    end of the record (H:495-544)."""
    sha = bytes(range(20))
    header = tool.local_header(5, 7, sha)
    assert struct.unpack_from("<q", header, 8)[0] == 5      # Size
    assert struct.unpack_from("<q", header, 16)[0] == 7     # UncompressedSize
    assert struct.unpack_from("<I", header, 24)[0] == 0     # method
    assert header[28:48] == sha
    assert header[48] == 0                                  # Flags
    assert struct.unpack_from("<I", header, 49)[0] == 0     # CompressionBlockSize


def test_local_header_rejects_wrong_hash_length():
    with pytest.raises(tool.PakWriteError):
        tool.local_header(1, 1, b"\x00" * 19)


def test_encoded_entry_is_twelve_bytes_with_the_expected_flag_word():
    """0xE0000000 == bits 31|30|29, method 0, unencrypted, zero blocks. This is
    the exact word our parser's census reports for both our containers and
    UnrealPak's own."""
    blob = tool.encode_entry(0, 5)
    assert len(blob) == 12
    assert struct.unpack_from("<I", blob, 0)[0] == 0xE0000000
    assert struct.unpack_from("<I", blob, 4)[0] == 0
    assert struct.unpack_from("<I", blob, 8)[0] == 5


def test_encoded_entry_omits_size_for_method_zero():
    """For method 0 the Size field is not emitted at all (C:7065); it is
    defined to equal UncompressedSize (C:7168-7170). Emitting it would shift
    every following byte while still parsing."""
    assert len(tool.encode_entry(10, 20)) == 12


def test_encoded_entry_refuses_oversized_fields_rather_than_truncating():
    with pytest.raises(tool.PakWriteError):
        tool.encode_entry(0x1_0000_0000, 5)


# --------------------------------------------------------------------------- #
# whole-container structure
# --------------------------------------------------------------------------- #

@pytest.fixture()
def built():
    return tool.build_pak(
        [("MISERY/Content/CT05/a.txt", b"alpha payload"),
         ("Engine/Content/CT05/b.txt", b"beta payload!!")],
        seed=0x1429B219)


def test_build_layout_tiles_the_file_exactly(built):
    layout = built["layout"]
    cursor = 0
    for key_off, key_size in (("index_offset", "index_size"),
                              ("path_hash_index_offset", "path_hash_index_size"),
                              ("full_directory_index_offset", "full_directory_index_size"),
                              ("footer_offset", "footer_size")):
        if key_off == "index_offset":
            assert layout[key_off] == layout["body_size"]
        else:
            assert layout[key_off] == cursor, key_off
        cursor = layout[key_off] + layout[key_size]
    assert cursor == layout["total_size"] == len(built["bytes"])


def test_build_reproduces_unrealpak_region_sizes(built):
    """Pinned against a container UnrealPak.exe generated from byte-identical
    input: body 133, primary 138, path-hash 32, full-dir 180, footer 221,
    total 704. A change in any of these means our layout diverged from Epic's."""
    layout = built["layout"]
    assert layout["body_size"] == 133
    assert layout["index_size"] == 138
    assert layout["path_hash_index_size"] == 32
    assert layout["full_directory_index_size"] == 180
    assert layout["footer_size"] == 221
    assert layout["total_size"] == 704


def test_footer_is_written_in_serialise_order_not_declaration_order(built):
    """The single easiest silent failure in this format. Footer discovery does
    not search for the magic -- it computes TotalSize - GetSerializedSize()
    (C:5989-6017) -- so a declaration-order footer is correctly sized and
    entirely wrong."""
    blob = built["bytes"]
    footer = blob[built["layout"]["footer_offset"]:]
    assert len(footer) == 221
    assert footer[0:16] == b"\x00" * 16                          # EncryptionKeyGuid
    assert footer[16] == 0                                       # bEncryptedIndex, 1 byte
    assert struct.unpack_from("<I", footer, 17)[0] == tool.PAK_MAGIC
    assert struct.unpack_from("<i", footer, 21)[0] == 11
    assert struct.unpack_from("<q", footer, 25)[0] == built["layout"]["index_offset"]
    assert struct.unpack_from("<q", footer, 33)[0] == built["layout"]["index_size"]
    assert footer[61:] == b"\x00" * 160                          # CompressionMethods


def test_footer_index_hash_covers_exactly_the_primary_index(built):
    blob = built["bytes"]
    layout = built["layout"]
    footer = blob[layout["footer_offset"]:]
    expected = hashlib.sha1(
        blob[layout["index_offset"]:layout["index_offset"] + layout["index_size"]]).digest()
    assert footer[41:61] == expected


def test_path_hash_blob_carries_the_pruned_directory_index_tail(built):
    """Trap 2: omitting this passes both project parsers and fails to mount,
    because C:6296 reads it in a Shipping build."""
    layout = built["layout"]
    blob = built["bytes"][layout["path_hash_index_offset"]:
                          layout["path_hash_index_offset"] + layout["path_hash_index_size"]]
    count = struct.unpack_from("<i", blob, 0)[0]
    assert count == 2
    consumed = 4 + count * 12
    assert len(blob) == consumed + 4, "an empty pruned index is exactly 4 more bytes"
    assert struct.unpack_from("<i", blob, consumed)[0] == 0


def test_keep_full_directory_in_pruned_slot_changes_only_that_blob():
    pruned = tool.build_pak([("A/x.txt", b"1")], seed=1, prune_directory_index=True)
    full = tool.build_pak([("A/x.txt", b"1")], seed=1, prune_directory_index=False)
    assert (full["layout"]["path_hash_index_size"]
            > pruned["layout"]["path_hash_index_size"])
    assert (full["layout"]["full_directory_index_size"]
            == pruned["layout"]["full_directory_index_size"])


def test_directory_index_contains_every_parent_including_root(built):
    directories = set(built["directory_index"])
    assert directories == {
        "/", "MISERY/", "MISERY/Content/", "MISERY/Content/CT05/",
        "Engine/", "Engine/Content/", "Engine/Content/CT05/"}


def test_every_path_resolves_through_the_path_hash_map(built):
    for directory, files in built["directory_index"].items():
        for filename, location in files.items():
            relative = filename if directory == "/" else directory + filename
            assert built["path_hash"][tool.hash_path(relative, built["seed"])] == location


def test_output_is_deterministic_for_a_fixed_seed():
    a = tool.build_pak([("A/x.txt", b"1"), ("B/y.txt", b"2")], seed=99)
    b = tool.build_pak([("A/x.txt", b"1"), ("B/y.txt", b"2")], seed=99)
    assert a["bytes"] == b["bytes"]


def test_self_test_passes_on_a_well_formed_container(built):
    for name, ok, detail in tool.self_test(built):
        assert ok, "%s failed: %s" % (name, detail)


# --------------------------------------------------------------------------- #
# refusals -- the writer must decline rather than emit something unvouchable
# --------------------------------------------------------------------------- #

def test_refuses_empty_container():
    with pytest.raises(tool.PakWriteError):
        tool.build_pak([])


def test_refuses_mount_point_not_in_directory_format():
    """AddEntryToIndex check()s this at C:6899."""
    with pytest.raises(tool.PakWriteError):
        tool.build_pak([("a.txt", b"x")], mount_point="../../..")


def test_refuses_leading_slash_in_index_path():
    with pytest.raises(tool.PakWriteError):
        tool.build_pak([("/a.txt", b"x")])


def test_refuses_duplicate_paths():
    with pytest.raises(tool.PakWriteError):
        tool.build_pak([("a.txt", b"x"), ("a.txt", b"y")])


# --------------------------------------------------------------------------- #
# end to end through the CLI, including the D-01 output guard
# --------------------------------------------------------------------------- #

def test_cli_writes_a_container_and_reports_layout(tmp_path):
    target = tmp_path / "cli.pak"
    rc = tool.main([str(target), "--add-literal", "hello=A/hello.txt"])
    assert rc == 0
    blob = target.read_bytes()
    assert len(blob) > 221
    footer = blob[-221:]
    assert struct.unpack_from("<I", footer, 17)[0] == tool.PAK_MAGIC


def test_cli_refuses_without_any_entries(tmp_path):
    assert tool.main([str(tmp_path / "empty.pak")]) == 2
