// GENERATED by tools/modplatform/genproxy.py -- do not edit.
#pragma once

#include <windows.h>

extern "C" {
extern void* MiseryReal_DwmpDxGetWindowSharedSurface;
extern void* MiseryReal_DwmpDxUpdateWindowSharedSurface;
extern void* MiseryReal_DwmEnableComposition;
extern void* MiseryReal_DllCanUnloadNow;
extern void* MiseryReal_DllGetClassObject;
extern void* MiseryReal_DwmAttachMilContent;
extern void* MiseryReal_DwmDefWindowProc;
extern void* MiseryReal_DwmDetachMilContent;
extern void* MiseryReal_DwmEnableBlurBehindWindow;
extern void* MiseryReal_DwmEnableMMCSS;
extern void* MiseryReal_DwmExtendFrameIntoClientArea;
extern void* MiseryReal_DwmFlush;
extern void* MiseryReal_DwmGetColorizationColor;
extern void* MiseryReal_DwmGetCompositionTimingInfo;
extern void* MiseryReal_DwmGetGraphicsStreamClient;
extern void* MiseryReal_DwmpGetColorizationParameters;
extern void* MiseryReal_DwmpDxgiIsThreadDesktopComposited;
extern void* MiseryReal_DwmGetGraphicsStreamTransformHint;
extern void* MiseryReal_DwmGetTransportAttributes;
extern void* MiseryReal_DwmpSetColorizationParameters;
extern void* MiseryReal_DwmGetUnmetTabRequirements;
extern void* MiseryReal_DwmGetWindowAttribute;
extern void* MiseryReal_DwmpRenderFlick;
extern void* MiseryReal_DwmpAllocateSecurityDescriptor;
extern void* MiseryReal_DwmpFreeSecurityDescriptor;
extern void* MiseryReal_DwmpEnableDDASupport;
extern void* MiseryReal_DwmInvalidateIconicBitmaps;
extern void* MiseryReal_DwmIsCompositionEnabled;
extern void* MiseryReal_DwmTetherTextContact;
extern void* MiseryReal_DwmpUpdateProxyWindowForCapture;
extern void* MiseryReal_DwmModifyPreviousDxFrameDuration;
extern void* MiseryReal_DwmQueryThumbnailSourceSize;
extern void* MiseryReal_DwmRegisterThumbnail;
extern void* MiseryReal_DwmRenderGesture;
extern void* MiseryReal_DwmSetDxFrameDuration;
extern void* MiseryReal_DwmSetIconicLivePreviewBitmap;
extern void* MiseryReal_DwmSetIconicThumbnail;
extern void* MiseryReal_DwmSetPresentParameters;
extern void* MiseryReal_DwmSetWindowAttribute;
extern void* MiseryReal_DwmShowContact;
extern void* MiseryReal_DwmTetherContact;
extern void* MiseryReal_DwmTransitionOwnedWindow;
extern void* MiseryReal_DwmUnregisterThumbnail;
extern void* MiseryReal_DwmUpdateThumbnailProperties;
}

// Fills the table from the REAL DLL. Returns false if any
// export is missing, because a half-filled table is a jump
// to a null pointer the first time somebody calls it.
inline bool MiseryBindReal(HMODULE real) {
    if (real == nullptr) return false;
    bool ok = true;
    MiseryReal_DwmpDxGetWindowSharedSurface = (void*)GetProcAddress(real, "DwmpDxGetWindowSharedSurface");
    if (MiseryReal_DwmpDxGetWindowSharedSurface == nullptr) ok = false;
    MiseryReal_DwmpDxUpdateWindowSharedSurface = (void*)GetProcAddress(real, "DwmpDxUpdateWindowSharedSurface");
    if (MiseryReal_DwmpDxUpdateWindowSharedSurface == nullptr) ok = false;
    MiseryReal_DwmEnableComposition = (void*)GetProcAddress(real, "DwmEnableComposition");
    if (MiseryReal_DwmEnableComposition == nullptr) ok = false;
    MiseryReal_DllCanUnloadNow = (void*)GetProcAddress(real, "DllCanUnloadNow");
    if (MiseryReal_DllCanUnloadNow == nullptr) ok = false;
    MiseryReal_DllGetClassObject = (void*)GetProcAddress(real, "DllGetClassObject");
    if (MiseryReal_DllGetClassObject == nullptr) ok = false;
    MiseryReal_DwmAttachMilContent = (void*)GetProcAddress(real, "DwmAttachMilContent");
    if (MiseryReal_DwmAttachMilContent == nullptr) ok = false;
    MiseryReal_DwmDefWindowProc = (void*)GetProcAddress(real, "DwmDefWindowProc");
    if (MiseryReal_DwmDefWindowProc == nullptr) ok = false;
    MiseryReal_DwmDetachMilContent = (void*)GetProcAddress(real, "DwmDetachMilContent");
    if (MiseryReal_DwmDetachMilContent == nullptr) ok = false;
    MiseryReal_DwmEnableBlurBehindWindow = (void*)GetProcAddress(real, "DwmEnableBlurBehindWindow");
    if (MiseryReal_DwmEnableBlurBehindWindow == nullptr) ok = false;
    MiseryReal_DwmEnableMMCSS = (void*)GetProcAddress(real, "DwmEnableMMCSS");
    if (MiseryReal_DwmEnableMMCSS == nullptr) ok = false;
    MiseryReal_DwmExtendFrameIntoClientArea = (void*)GetProcAddress(real, "DwmExtendFrameIntoClientArea");
    if (MiseryReal_DwmExtendFrameIntoClientArea == nullptr) ok = false;
    MiseryReal_DwmFlush = (void*)GetProcAddress(real, "DwmFlush");
    if (MiseryReal_DwmFlush == nullptr) ok = false;
    MiseryReal_DwmGetColorizationColor = (void*)GetProcAddress(real, "DwmGetColorizationColor");
    if (MiseryReal_DwmGetColorizationColor == nullptr) ok = false;
    MiseryReal_DwmGetCompositionTimingInfo = (void*)GetProcAddress(real, "DwmGetCompositionTimingInfo");
    if (MiseryReal_DwmGetCompositionTimingInfo == nullptr) ok = false;
    MiseryReal_DwmGetGraphicsStreamClient = (void*)GetProcAddress(real, "DwmGetGraphicsStreamClient");
    if (MiseryReal_DwmGetGraphicsStreamClient == nullptr) ok = false;
    MiseryReal_DwmpGetColorizationParameters = (void*)GetProcAddress(real, "DwmpGetColorizationParameters");
    if (MiseryReal_DwmpGetColorizationParameters == nullptr) ok = false;
    MiseryReal_DwmpDxgiIsThreadDesktopComposited = (void*)GetProcAddress(real, "DwmpDxgiIsThreadDesktopComposited");
    if (MiseryReal_DwmpDxgiIsThreadDesktopComposited == nullptr) ok = false;
    MiseryReal_DwmGetGraphicsStreamTransformHint = (void*)GetProcAddress(real, "DwmGetGraphicsStreamTransformHint");
    if (MiseryReal_DwmGetGraphicsStreamTransformHint == nullptr) ok = false;
    MiseryReal_DwmGetTransportAttributes = (void*)GetProcAddress(real, "DwmGetTransportAttributes");
    if (MiseryReal_DwmGetTransportAttributes == nullptr) ok = false;
    MiseryReal_DwmpSetColorizationParameters = (void*)GetProcAddress(real, "DwmpSetColorizationParameters");
    if (MiseryReal_DwmpSetColorizationParameters == nullptr) ok = false;
    MiseryReal_DwmGetUnmetTabRequirements = (void*)GetProcAddress(real, "DwmGetUnmetTabRequirements");
    if (MiseryReal_DwmGetUnmetTabRequirements == nullptr) ok = false;
    MiseryReal_DwmGetWindowAttribute = (void*)GetProcAddress(real, "DwmGetWindowAttribute");
    if (MiseryReal_DwmGetWindowAttribute == nullptr) ok = false;
    MiseryReal_DwmpRenderFlick = (void*)GetProcAddress(real, "DwmpRenderFlick");
    if (MiseryReal_DwmpRenderFlick == nullptr) ok = false;
    MiseryReal_DwmpAllocateSecurityDescriptor = (void*)GetProcAddress(real, "DwmpAllocateSecurityDescriptor");
    if (MiseryReal_DwmpAllocateSecurityDescriptor == nullptr) ok = false;
    MiseryReal_DwmpFreeSecurityDescriptor = (void*)GetProcAddress(real, "DwmpFreeSecurityDescriptor");
    if (MiseryReal_DwmpFreeSecurityDescriptor == nullptr) ok = false;
    MiseryReal_DwmpEnableDDASupport = (void*)GetProcAddress(real, "DwmpEnableDDASupport");
    if (MiseryReal_DwmpEnableDDASupport == nullptr) ok = false;
    MiseryReal_DwmInvalidateIconicBitmaps = (void*)GetProcAddress(real, "DwmInvalidateIconicBitmaps");
    if (MiseryReal_DwmInvalidateIconicBitmaps == nullptr) ok = false;
    MiseryReal_DwmIsCompositionEnabled = (void*)GetProcAddress(real, "DwmIsCompositionEnabled");
    if (MiseryReal_DwmIsCompositionEnabled == nullptr) ok = false;
    MiseryReal_DwmTetherTextContact = (void*)GetProcAddress(real, "DwmTetherTextContact");
    if (MiseryReal_DwmTetherTextContact == nullptr) ok = false;
    MiseryReal_DwmpUpdateProxyWindowForCapture = (void*)GetProcAddress(real, "DwmpUpdateProxyWindowForCapture");
    if (MiseryReal_DwmpUpdateProxyWindowForCapture == nullptr) ok = false;
    MiseryReal_DwmModifyPreviousDxFrameDuration = (void*)GetProcAddress(real, "DwmModifyPreviousDxFrameDuration");
    if (MiseryReal_DwmModifyPreviousDxFrameDuration == nullptr) ok = false;
    MiseryReal_DwmQueryThumbnailSourceSize = (void*)GetProcAddress(real, "DwmQueryThumbnailSourceSize");
    if (MiseryReal_DwmQueryThumbnailSourceSize == nullptr) ok = false;
    MiseryReal_DwmRegisterThumbnail = (void*)GetProcAddress(real, "DwmRegisterThumbnail");
    if (MiseryReal_DwmRegisterThumbnail == nullptr) ok = false;
    MiseryReal_DwmRenderGesture = (void*)GetProcAddress(real, "DwmRenderGesture");
    if (MiseryReal_DwmRenderGesture == nullptr) ok = false;
    MiseryReal_DwmSetDxFrameDuration = (void*)GetProcAddress(real, "DwmSetDxFrameDuration");
    if (MiseryReal_DwmSetDxFrameDuration == nullptr) ok = false;
    MiseryReal_DwmSetIconicLivePreviewBitmap = (void*)GetProcAddress(real, "DwmSetIconicLivePreviewBitmap");
    if (MiseryReal_DwmSetIconicLivePreviewBitmap == nullptr) ok = false;
    MiseryReal_DwmSetIconicThumbnail = (void*)GetProcAddress(real, "DwmSetIconicThumbnail");
    if (MiseryReal_DwmSetIconicThumbnail == nullptr) ok = false;
    MiseryReal_DwmSetPresentParameters = (void*)GetProcAddress(real, "DwmSetPresentParameters");
    if (MiseryReal_DwmSetPresentParameters == nullptr) ok = false;
    MiseryReal_DwmSetWindowAttribute = (void*)GetProcAddress(real, "DwmSetWindowAttribute");
    if (MiseryReal_DwmSetWindowAttribute == nullptr) ok = false;
    MiseryReal_DwmShowContact = (void*)GetProcAddress(real, "DwmShowContact");
    if (MiseryReal_DwmShowContact == nullptr) ok = false;
    MiseryReal_DwmTetherContact = (void*)GetProcAddress(real, "DwmTetherContact");
    if (MiseryReal_DwmTetherContact == nullptr) ok = false;
    MiseryReal_DwmTransitionOwnedWindow = (void*)GetProcAddress(real, "DwmTransitionOwnedWindow");
    if (MiseryReal_DwmTransitionOwnedWindow == nullptr) ok = false;
    MiseryReal_DwmUnregisterThumbnail = (void*)GetProcAddress(real, "DwmUnregisterThumbnail");
    if (MiseryReal_DwmUnregisterThumbnail == nullptr) ok = false;
    MiseryReal_DwmUpdateThumbnailProperties = (void*)GetProcAddress(real, "DwmUpdateThumbnailProperties");
    if (MiseryReal_DwmUpdateThumbnailProperties == nullptr) ok = false;
    return ok;
}

#define MISERY_PROXY_EXPORT_COUNT 44
