; GENERATED by tools/modplatform/genproxy.py -- do not edit.
;
; One jump per export, through a pointer the C side fills in. A jump is
; exactly correct for every signature and calling convention precisely
; because it never touches the arguments: the callee returns straight to
; the original caller and the stack is untouched.

.code

EXTERN MiseryReal_DwmpDxGetWindowSharedSurface:QWORD
EXTERN MiseryReal_DwmpDxUpdateWindowSharedSurface:QWORD
EXTERN MiseryReal_DwmEnableComposition:QWORD
EXTERN MiseryReal_DllCanUnloadNow:QWORD
EXTERN MiseryReal_DllGetClassObject:QWORD
EXTERN MiseryReal_DwmAttachMilContent:QWORD
EXTERN MiseryReal_DwmDefWindowProc:QWORD
EXTERN MiseryReal_DwmDetachMilContent:QWORD
EXTERN MiseryReal_DwmEnableBlurBehindWindow:QWORD
EXTERN MiseryReal_DwmEnableMMCSS:QWORD
EXTERN MiseryReal_DwmExtendFrameIntoClientArea:QWORD
EXTERN MiseryReal_DwmFlush:QWORD
EXTERN MiseryReal_DwmGetColorizationColor:QWORD
EXTERN MiseryReal_DwmGetCompositionTimingInfo:QWORD
EXTERN MiseryReal_DwmGetGraphicsStreamClient:QWORD
EXTERN MiseryReal_DwmpGetColorizationParameters:QWORD
EXTERN MiseryReal_DwmpDxgiIsThreadDesktopComposited:QWORD
EXTERN MiseryReal_DwmGetGraphicsStreamTransformHint:QWORD
EXTERN MiseryReal_DwmGetTransportAttributes:QWORD
EXTERN MiseryReal_DwmpSetColorizationParameters:QWORD
EXTERN MiseryReal_DwmGetUnmetTabRequirements:QWORD
EXTERN MiseryReal_DwmGetWindowAttribute:QWORD
EXTERN MiseryReal_DwmpRenderFlick:QWORD
EXTERN MiseryReal_DwmpAllocateSecurityDescriptor:QWORD
EXTERN MiseryReal_DwmpFreeSecurityDescriptor:QWORD
EXTERN MiseryReal_DwmpEnableDDASupport:QWORD
EXTERN MiseryReal_DwmInvalidateIconicBitmaps:QWORD
EXTERN MiseryReal_DwmIsCompositionEnabled:QWORD
EXTERN MiseryReal_DwmTetherTextContact:QWORD
EXTERN MiseryReal_DwmpUpdateProxyWindowForCapture:QWORD
EXTERN MiseryReal_DwmModifyPreviousDxFrameDuration:QWORD
EXTERN MiseryReal_DwmQueryThumbnailSourceSize:QWORD
EXTERN MiseryReal_DwmRegisterThumbnail:QWORD
EXTERN MiseryReal_DwmRenderGesture:QWORD
EXTERN MiseryReal_DwmSetDxFrameDuration:QWORD
EXTERN MiseryReal_DwmSetIconicLivePreviewBitmap:QWORD
EXTERN MiseryReal_DwmSetIconicThumbnail:QWORD
EXTERN MiseryReal_DwmSetPresentParameters:QWORD
EXTERN MiseryReal_DwmSetWindowAttribute:QWORD
EXTERN MiseryReal_DwmShowContact:QWORD
EXTERN MiseryReal_DwmTetherContact:QWORD
EXTERN MiseryReal_DwmTransitionOwnedWindow:QWORD
EXTERN MiseryReal_DwmUnregisterThumbnail:QWORD
EXTERN MiseryReal_DwmUpdateThumbnailProperties:QWORD

DwmpDxGetWindowSharedSurface PROC
    jmp qword ptr [MiseryReal_DwmpDxGetWindowSharedSurface]
DwmpDxGetWindowSharedSurface ENDP

DwmpDxUpdateWindowSharedSurface PROC
    jmp qword ptr [MiseryReal_DwmpDxUpdateWindowSharedSurface]
DwmpDxUpdateWindowSharedSurface ENDP

DwmEnableComposition PROC
    jmp qword ptr [MiseryReal_DwmEnableComposition]
DwmEnableComposition ENDP

DllCanUnloadNow PROC
    jmp qword ptr [MiseryReal_DllCanUnloadNow]
DllCanUnloadNow ENDP

DllGetClassObject PROC
    jmp qword ptr [MiseryReal_DllGetClassObject]
DllGetClassObject ENDP

DwmAttachMilContent PROC
    jmp qword ptr [MiseryReal_DwmAttachMilContent]
DwmAttachMilContent ENDP

DwmDefWindowProc PROC
    jmp qword ptr [MiseryReal_DwmDefWindowProc]
DwmDefWindowProc ENDP

DwmDetachMilContent PROC
    jmp qword ptr [MiseryReal_DwmDetachMilContent]
DwmDetachMilContent ENDP

DwmEnableBlurBehindWindow PROC
    jmp qword ptr [MiseryReal_DwmEnableBlurBehindWindow]
DwmEnableBlurBehindWindow ENDP

DwmEnableMMCSS PROC
    jmp qword ptr [MiseryReal_DwmEnableMMCSS]
DwmEnableMMCSS ENDP

DwmExtendFrameIntoClientArea PROC
    jmp qword ptr [MiseryReal_DwmExtendFrameIntoClientArea]
DwmExtendFrameIntoClientArea ENDP

DwmFlush PROC
    jmp qword ptr [MiseryReal_DwmFlush]
DwmFlush ENDP

DwmGetColorizationColor PROC
    jmp qword ptr [MiseryReal_DwmGetColorizationColor]
DwmGetColorizationColor ENDP

DwmGetCompositionTimingInfo PROC
    jmp qword ptr [MiseryReal_DwmGetCompositionTimingInfo]
DwmGetCompositionTimingInfo ENDP

DwmGetGraphicsStreamClient PROC
    jmp qword ptr [MiseryReal_DwmGetGraphicsStreamClient]
DwmGetGraphicsStreamClient ENDP

DwmpGetColorizationParameters PROC
    jmp qword ptr [MiseryReal_DwmpGetColorizationParameters]
DwmpGetColorizationParameters ENDP

DwmpDxgiIsThreadDesktopComposited PROC
    jmp qword ptr [MiseryReal_DwmpDxgiIsThreadDesktopComposited]
DwmpDxgiIsThreadDesktopComposited ENDP

DwmGetGraphicsStreamTransformHint PROC
    jmp qword ptr [MiseryReal_DwmGetGraphicsStreamTransformHint]
DwmGetGraphicsStreamTransformHint ENDP

DwmGetTransportAttributes PROC
    jmp qword ptr [MiseryReal_DwmGetTransportAttributes]
DwmGetTransportAttributes ENDP

DwmpSetColorizationParameters PROC
    jmp qword ptr [MiseryReal_DwmpSetColorizationParameters]
DwmpSetColorizationParameters ENDP

DwmGetUnmetTabRequirements PROC
    jmp qword ptr [MiseryReal_DwmGetUnmetTabRequirements]
DwmGetUnmetTabRequirements ENDP

DwmGetWindowAttribute PROC
    jmp qword ptr [MiseryReal_DwmGetWindowAttribute]
DwmGetWindowAttribute ENDP

DwmpRenderFlick PROC
    jmp qword ptr [MiseryReal_DwmpRenderFlick]
DwmpRenderFlick ENDP

DwmpAllocateSecurityDescriptor PROC
    jmp qword ptr [MiseryReal_DwmpAllocateSecurityDescriptor]
DwmpAllocateSecurityDescriptor ENDP

DwmpFreeSecurityDescriptor PROC
    jmp qword ptr [MiseryReal_DwmpFreeSecurityDescriptor]
DwmpFreeSecurityDescriptor ENDP

DwmpEnableDDASupport PROC
    jmp qword ptr [MiseryReal_DwmpEnableDDASupport]
DwmpEnableDDASupport ENDP

DwmInvalidateIconicBitmaps PROC
    jmp qword ptr [MiseryReal_DwmInvalidateIconicBitmaps]
DwmInvalidateIconicBitmaps ENDP

DwmIsCompositionEnabled PROC
    jmp qword ptr [MiseryReal_DwmIsCompositionEnabled]
DwmIsCompositionEnabled ENDP

DwmTetherTextContact PROC
    jmp qword ptr [MiseryReal_DwmTetherTextContact]
DwmTetherTextContact ENDP

DwmpUpdateProxyWindowForCapture PROC
    jmp qword ptr [MiseryReal_DwmpUpdateProxyWindowForCapture]
DwmpUpdateProxyWindowForCapture ENDP

DwmModifyPreviousDxFrameDuration PROC
    jmp qword ptr [MiseryReal_DwmModifyPreviousDxFrameDuration]
DwmModifyPreviousDxFrameDuration ENDP

DwmQueryThumbnailSourceSize PROC
    jmp qword ptr [MiseryReal_DwmQueryThumbnailSourceSize]
DwmQueryThumbnailSourceSize ENDP

DwmRegisterThumbnail PROC
    jmp qword ptr [MiseryReal_DwmRegisterThumbnail]
DwmRegisterThumbnail ENDP

DwmRenderGesture PROC
    jmp qword ptr [MiseryReal_DwmRenderGesture]
DwmRenderGesture ENDP

DwmSetDxFrameDuration PROC
    jmp qword ptr [MiseryReal_DwmSetDxFrameDuration]
DwmSetDxFrameDuration ENDP

DwmSetIconicLivePreviewBitmap PROC
    jmp qword ptr [MiseryReal_DwmSetIconicLivePreviewBitmap]
DwmSetIconicLivePreviewBitmap ENDP

DwmSetIconicThumbnail PROC
    jmp qword ptr [MiseryReal_DwmSetIconicThumbnail]
DwmSetIconicThumbnail ENDP

DwmSetPresentParameters PROC
    jmp qword ptr [MiseryReal_DwmSetPresentParameters]
DwmSetPresentParameters ENDP

DwmSetWindowAttribute PROC
    jmp qword ptr [MiseryReal_DwmSetWindowAttribute]
DwmSetWindowAttribute ENDP

DwmShowContact PROC
    jmp qword ptr [MiseryReal_DwmShowContact]
DwmShowContact ENDP

DwmTetherContact PROC
    jmp qword ptr [MiseryReal_DwmTetherContact]
DwmTetherContact ENDP

DwmTransitionOwnedWindow PROC
    jmp qword ptr [MiseryReal_DwmTransitionOwnedWindow]
DwmTransitionOwnedWindow ENDP

DwmUnregisterThumbnail PROC
    jmp qword ptr [MiseryReal_DwmUnregisterThumbnail]
DwmUnregisterThumbnail ENDP

DwmUpdateThumbnailProperties PROC
    jmp qword ptr [MiseryReal_DwmUpdateThumbnailProperties]
DwmUpdateThumbnailProperties ENDP

END
