// GENERATED by tools/modplatform/genproxy.py -- do not edit.
#include "dwmapi_proxy.h"

extern "C" {
void* MiseryReal_DwmpDxGetWindowSharedSurface = nullptr;
void* MiseryReal_DwmpDxUpdateWindowSharedSurface = nullptr;
void* MiseryReal_DwmEnableComposition = nullptr;
void* MiseryReal_DllCanUnloadNow = nullptr;
void* MiseryReal_DllGetClassObject = nullptr;
void* MiseryReal_DwmAttachMilContent = nullptr;
void* MiseryReal_DwmDefWindowProc = nullptr;
void* MiseryReal_DwmDetachMilContent = nullptr;
void* MiseryReal_DwmEnableBlurBehindWindow = nullptr;
void* MiseryReal_DwmEnableMMCSS = nullptr;
void* MiseryReal_DwmExtendFrameIntoClientArea = nullptr;
void* MiseryReal_DwmFlush = nullptr;
void* MiseryReal_DwmGetColorizationColor = nullptr;
void* MiseryReal_DwmGetCompositionTimingInfo = nullptr;
void* MiseryReal_DwmGetGraphicsStreamClient = nullptr;
void* MiseryReal_DwmpGetColorizationParameters = nullptr;
void* MiseryReal_DwmpDxgiIsThreadDesktopComposited = nullptr;
void* MiseryReal_DwmGetGraphicsStreamTransformHint = nullptr;
void* MiseryReal_DwmGetTransportAttributes = nullptr;
void* MiseryReal_DwmpSetColorizationParameters = nullptr;
void* MiseryReal_DwmGetUnmetTabRequirements = nullptr;
void* MiseryReal_DwmGetWindowAttribute = nullptr;
void* MiseryReal_DwmpRenderFlick = nullptr;
void* MiseryReal_DwmpAllocateSecurityDescriptor = nullptr;
void* MiseryReal_DwmpFreeSecurityDescriptor = nullptr;
void* MiseryReal_DwmpEnableDDASupport = nullptr;
void* MiseryReal_DwmInvalidateIconicBitmaps = nullptr;
void* MiseryReal_DwmIsCompositionEnabled = nullptr;
void* MiseryReal_DwmTetherTextContact = nullptr;
void* MiseryReal_DwmpUpdateProxyWindowForCapture = nullptr;
void* MiseryReal_DwmModifyPreviousDxFrameDuration = nullptr;
void* MiseryReal_DwmQueryThumbnailSourceSize = nullptr;
void* MiseryReal_DwmRegisterThumbnail = nullptr;
void* MiseryReal_DwmRenderGesture = nullptr;
void* MiseryReal_DwmSetDxFrameDuration = nullptr;
void* MiseryReal_DwmSetIconicLivePreviewBitmap = nullptr;
void* MiseryReal_DwmSetIconicThumbnail = nullptr;
void* MiseryReal_DwmSetPresentParameters = nullptr;
void* MiseryReal_DwmSetWindowAttribute = nullptr;
void* MiseryReal_DwmShowContact = nullptr;
void* MiseryReal_DwmTetherContact = nullptr;
void* MiseryReal_DwmTransitionOwnedWindow = nullptr;
void* MiseryReal_DwmUnregisterThumbnail = nullptr;
void* MiseryReal_DwmUpdateThumbnailProperties = nullptr;
}
