#!/usr/bin/env python3
"""Generate the forwarding proxy for a system DLL, from that DLL's own exports.

WHY A PROXY AT ALL
------------------
Stage 5B has to remove the research controller from the normal launch path,
which means something of ours must be in the process before the game's own code
runs -- with no injector, no launcher and no Steam configuration. On Windows the
only mechanism that does that without touching the executable is the application
directory taking precedence in the DLL search order: a DLL of the right name
placed beside the .exe is loaded by the loader itself, as part of resolving the
game's imports.

WHY dwmapi
----------
MISERY-Win64-Shipping.exe imports four functions from it. It is a small, stable,
leaf system DLL that does not call back into the application, and there is no
dwmapi.dll in the game's Binaries directory, so nothing is overwritten.

WHY THIS IS GENERATED
---------------------
A proxy must export EVERYTHING the real DLL does, not just the four the game
uses: any other module in the process -- the Steam overlay, a driver shim, a
plugin -- may import a different one, and a missing export makes that module
fail to load. Forty-four hand-written stubs would be forty-four chances to get a
signature wrong, and they would silently rot when Windows adds an export.

So the table is read from the real DLL and the thunks are ASSEMBLY: a jump
through a pointer, which is exactly correct for every calling convention and
every signature, because it never touches the arguments at all. Ordinals are
preserved too, since an importer is allowed to bind by ordinal.
"""
import argparse
import os
import struct

SYSTEM32 = os.path.join(os.environ.get("SystemRoot", r"C:\Windows"), "System32")


def read_exports(path):
    """Every named export of a PE, with its ordinal. Read, never assumed."""
    with open(path, "rb") as handle:
        raw = handle.read()
    pe = struct.unpack_from("<I", raw, 0x3C)[0]
    if raw[pe:pe + 4] != b"PE\0\0":
        raise ValueError("%s is not a PE" % path)
    opt = pe + 24
    magic = struct.unpack_from("<H", raw, opt)[0]
    sections = struct.unpack_from("<H", raw, pe + 6)[0]
    opt_size = struct.unpack_from("<H", raw, pe + 20)[0]
    directory = opt + (112 if magic == 0x20B else 96)
    export_rva, _size = struct.unpack_from("<II", raw, directory)

    table = []
    offset = opt + opt_size
    for _ in range(sections):
        vsize, vaddr, rsize, raddr = struct.unpack_from("<IIII", raw, offset + 8)
        table.append((vaddr, vsize, raddr, rsize))
        offset += 40

    def to_offset(rva):
        for vaddr, vsize, raddr, rsize in table:
            if vaddr <= rva < vaddr + max(vsize, rsize):
                return raddr + (rva - vaddr)
        raise ValueError("rva 0x%x is outside every section" % rva)

    base = to_offset(export_rva)
    (_flags, _stamp, _major, _name_rva, ordinal_base, _naddr, name_count,
     _addr_rva, names_rva, ords_rva) = struct.unpack_from("<IIIIIIIIII", raw, base)

    exports = []
    for index in range(name_count):
        name_ptr = struct.unpack_from("<I", raw, to_offset(names_rva) + 4 * index)[0]
        start = to_offset(name_ptr)
        name = raw[start:raw.index(b"\0", start)].decode("ascii")
        ordinal = struct.unpack_from("<H", raw,
                                     to_offset(ords_rva) + 2 * index)[0]
        exports.append((name, ordinal + ordinal_base))
    exports.sort(key=lambda entry: entry[1])
    return exports


def emit(module, exports, out_dir):
    """Write the .asm thunks, the .def and the pointer table header."""
    os.makedirs(out_dir, exist_ok=True)
    stem = module.replace(".dll", "")

    asm = [
        "; GENERATED by tools/modplatform/genproxy.py -- do not edit.",
        ";",
        "; One jump per export, through a pointer the C side fills in. A jump is",
        "; exactly correct for every signature and calling convention precisely",
        "; because it never touches the arguments: the callee returns straight to",
        "; the original caller and the stack is untouched.",
        "",
        ".code",
        "",
    ]
    for name, _ordinal in exports:
        asm.append("EXTERN MiseryReal_%s:QWORD" % name)
    asm.append("")
    for name, _ordinal in exports:
        asm.append("%s PROC" % name)
        asm.append("    jmp qword ptr [MiseryReal_%s]" % name)
        asm.append("%s ENDP" % name)
        asm.append("")
    asm.append("END")

    defs = ["; GENERATED by tools/modplatform/genproxy.py -- do not edit.",
            "EXPORTS"]
    for name, ordinal in exports:
        # Ordinals preserved: an importer may bind by ordinal, and a proxy whose
        # ordinals differ would hand it the wrong function.
        defs.append("    %s @%d" % (name, ordinal))

    header = [
        "// GENERATED by tools/modplatform/genproxy.py -- do not edit.",
        "#pragma once",
        "",
        "#include <windows.h>",
        "",
        "extern \"C\" {",
    ]
    for name, _ordinal in exports:
        header.append("extern void* MiseryReal_%s;" % name)
    header.append("}")
    header.append("")
    header.append("// Fills the table from the REAL DLL. Returns false if any")
    header.append("// export is missing, because a half-filled table is a jump")
    header.append("// to a null pointer the first time somebody calls it.")
    header.append("inline bool MiseryBindReal(HMODULE real) {")
    header.append("    if (real == nullptr) return false;")
    header.append("    bool ok = true;")
    for name, _ordinal in exports:
        header.append('    MiseryReal_%s = (void*)GetProcAddress(real, "%s");'
                      % (name, name))
        header.append("    if (MiseryReal_%s == nullptr) ok = false;" % name)
    header.append("    return ok;")
    header.append("}")
    header.append("")
    header.append("#define MISERY_PROXY_EXPORT_COUNT %d" % len(exports))

    storage = ["// GENERATED by tools/modplatform/genproxy.py -- do not edit.",
               '#include "%s_proxy.h"' % stem, "", 'extern "C" {']
    for name, _ordinal in exports:
        storage.append("void* MiseryReal_%s = nullptr;" % name)
    storage.append("}")

    paths = {}
    for suffix, lines in (("_proxy.asm", asm), ("_proxy.def", defs),
                          ("_proxy.h", header), ("_proxy.cpp", storage)):
        path = os.path.join(out_dir, stem + suffix)
        with open(path, "w", encoding="utf-8", newline="\r\n"
                  if suffix == "_proxy.asm" else "\n") as handle:
            handle.write("\n".join(lines) + "\n")
        paths[suffix] = path
    return paths


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--module", default="dwmapi.dll")
    ap.add_argument("--source", default=None,
                    help="the real DLL to read exports from")
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)
    source = a.source or os.path.join(SYSTEM32, a.module)
    exports = read_exports(source)
    paths = emit(a.module, exports, a.out)
    print("%s: %d exports -> %s" % (a.module, len(exports), a.out))
    for suffix, path in sorted(paths.items()):
        print("   %s" % os.path.basename(path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
